# Generated by Django 3.1 on 2020-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(default='EBB', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default='0000000000', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(default='EBB', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='BAN', max_length=30),
        ),
    ]
