# Generated by Django 3.1.1 on 2020-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200819_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardWareForm_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetNo', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('AssetTypeModel', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=50)),
                ('TeamName', models.CharField(max_length=50)),
                ('ProductLine', models.CharField(max_length=50)),
                ('Remark', models.CharField(max_length=400)),
            ],
        ),
    ]
